### ISSUE TITLE
Cannot be installed with up-to-date versions of Node/NPM

### ISSUE THREAD

**Issue by hubjongit** [dilidili/react-drawing-board#29]
Running the `npm install react-drawing-board` on a fresh project results in many warnings and errors. It seems that the listed dependencies in the package.json have changed names or location at this time, and are therefore inaccessible and result in a failed installation.

Here is the output from the command:
```
npm WARN ERESOLVE overriding peer dependency
npm WARN ERESOLVE overriding peer dependency
npm WARN ERESOLVE overriding peer dependency
npm WARN ERESOLVE overriding peer dependency
npm WARN ERESOLVE overriding peer dependency
npm WARN ERESOLVE overriding peer dependency
npm WARN ERESOLVE overriding peer dependency
npm WARN ERESOLVE overriding peer dependency
npm WARN ERESOLVE overriding peer dependency
npm WARN ERESOLVE overriding peer dependency
npm WARN ERESOLVE overriding peer dependency
npm WARN ERESOLVE overriding peer dependency
npm WARN ERESOLVE overriding peer dependency
npm WARN ERESOLVE overriding peer dependency
npm WARN ERESOLVE overriding peer dependency
npm WARN ERESOLVE overriding peer dependency
npm WARN ERESOLVE overriding peer dependency
npm WARN ERESOLVE overriding peer dependency
npm WARN ERESOLVE overriding peer dependency
npm WARN ERESOLVE overriding peer dependency
npm WARN deprecated @types/vfile-message@2.0.0: This is a stub types definition. vfile-message provides its own type definitions, so you do not need this installed.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated react-use-gesture@7.0.16: This package is no longer maintained. Please use @use-gesture/react instead
npm WARN deprecated intl-messageformat-parser@3.6.4: We've written a new parser that's 6x faster and is backwards compatible. Please use @formatjs/icu-messageformat-parser
npm WARN deprecated @formatjs/intl-utils@2.3.0: the package is rather renamed to @formatjs/ecma-abstract with some changes in functionality (primarily selectUnit is removed and we don't plan to make any further changes to this package
npm WARN deprecated core-js@1.2.7: core-js@<3.4 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
npm WARN deprecated core-js@2.6.12: core-js@<3.4 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
npm WARN deprecated @formatjs/intl-unified-numberformat@3.3.7: We have renamed the package to @formatjs/intl-numberformat
npm ERR! code 1
npm ERR! path /Users/.../node_modules/react-drawing-board
npm ERR! command failed
npm ERR! command sh -c node scripts/postinstall.js
npm ERR! [ERR] Error removing Antd Global Styles: Error: No files match the pattern: /Users/.../node_modules/react-drawing-board/node_modules/antd/lib/style/core/index.less
npm ERR!     at /Users/.../node_modules/replace-in-file/lib/helpers/glob-async.js:27:23
npm ERR!     at f (/Users/.../node_modules/once/once.js:25:25)
npm ERR!     at Glob.<anonymous> (/Users/.../node_modules/glob/glob.js:148:7)
npm ERR!     at Glob.emit (node:events:527:28)
npm ERR!     at Glob._finish (/Users/.../node_modules/glob/glob.js:194:8)
npm ERR!     at done (/Users/.../node_modules/glob/glob.js:179:14)
npm ERR!     at Glob._processSimple2 (/Users/.../node_modules/glob/glob.js:685:12)
npm ERR!     at /Users/.../node_modules/glob/glob.js:673:10
npm ERR!     at Glob._stat2 (/Users/.../node_modules/glob/glob.js:769:12)
npm ERR!     at lstatcb_ (/Users/.../node_modules/glob/glob.js:761:12)

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/.../.npm/_logs/2022-04-20T05_31_47_336Z-debug-0.log
```

**Comment by omaranBazna** [comment]
same here

**Comment by zalavadiyamayur** [comment]
same here

**Comment by zalavadiyamayur** [comment]
npm ERR! command failed
npm ERR! command sh -c -- node scripts/postinstall.js

**Comment by bunpitak-inno5** [comment]
npm install antd
it work for me

**Comment by MeSawSomething** [comment]
same issue
